#!/usr/bin/env python3
"""Generate a Lean-checkable refutation tree for the k=11 finite modulus domain.

The Python search only proposes one local obstruction per rejected prefix. Lean
checks every obstruction and every branch; this script is not a proof engine.
"""

from collections import Counter
from itertools import combinations
from math import gcd, lcm
from pathlib import Path

from enumerate import domain

TARGET = Path(__file__).resolve().parents[1] / "lean/ProofPursuit/P4/ElevenCertificate.lean"
BEGIN = "-- BEGIN GENERATED CERTIFICATE\n"
END = "-- END GENERATED CERTIFICATE\n"

ordered = domain(11)
values = tuple(x for x in ordered if x % 10 == 0) + tuple(x for x in ordered if x % 10)
assert len(values) == 40
assert sum(x % 10 == 0 for x in values) == 18

stats = Counter()


def allowed(pre):
    start = pre[-1] if pre else 0
    stop = 18 if len(pre) < 3 else 40
    return tuple(
        rank for rank in range(start, stop)
        if all(1 < gcd(values[y], values[rank]) < 11 for y in pre)
    )


def bad_density_with_newest(pre):
    if not pre:
        return None
    last = len(pre) - 1
    for size in range(2, len(pre) + 1):
        for earlier in combinations(range(last), size - 1):
            positions = earlier + (last,)
            selected = tuple(values[pre[i]] for i in positions)
            period = lcm(*(gcd(x, y) for x, y in combinations(selected, 2)))
            occupied = sum(period // gcd(x, period) for x in selected)
            if occupied > period:
                mask = sum(1 << i for i in positions)
                return (mask, period)
    return None


def tree(pre):
    stats[f"visited_{len(pre)}"] += 1
    bad = bad_density_with_newest(pre)
    if bad is not None:
        stats["density_leaves"] += 1
        return ("density", *bad)
    if len(pre) == 11:
        raise RuntimeError(f"unrejected length-11 list: {[values[i] for i in pre]}")
    children = tuple(tree(pre + (rank,)) for rank in allowed(pre))
    stats["branch_nodes"] += 1
    return ("branch", children)


def emit(node, out):
    if node[0] == "density":
        out.append(f"Cert.density {node[1]} {node[2]}")
    else:
        out.append("Cert.branch [")
        for index, child in enumerate(node[1]):
            if index:
                out.append(",")
            emit(child, out)
        out.append("]")


def main():
    content = TARGET.read_text()
    head, rest = content.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    cert = tree(())
    pieces = []
    emit(cert, pieces)
    generated = (
        "set_option maxRecDepth 10000\n"
        "set_option maxHeartbeats 0\n\n"
        "def certificate : Cert := " + "".join(pieces) + "\n\n"
        "theorem certificate_checked : check 11 [] certificate = true := by decide\n\n"
        "theorem no_candidate : ¬ ∃ xs, Candidate [] 11 xs := by\n"
        "  rintro ⟨xs, hxs⟩\n"
        "  exact check_sound 11 [] certificate certificate_checked xs hxs\n\n"
        "#print axioms no_candidate\n"
    )
    TARGET.write_text(head + BEGIN + generated + END + tail)
    print("generated bytes", len(generated), "stats", dict(sorted(stats.items())))


if __name__ == "__main__":
    main()
