#!/usr/bin/env python3
"""Rebuild standalone problem and cell TeX editions from pinned Markdown."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
from urllib.parse import quote, urlsplit

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
MANIFEST = json.loads((HERE / "sources.json").read_text(encoding="utf-8"))
COMMIT = MANIFEST["source_commit"]
BASE = f"https://github.com/mpelteshki/climbing-to-the-frontier/blob/{COMMIT}/"
SOURCE = {
    "p1": ROOT / "cagent/p1/writeup.md",
    "p2": ROOT / "cagent/p2/writeup.md",
    "p3": HERE / "p3-source.md",
    "p4": ROOT / "cagent/p4/SUBMISSION.md",
    "p1-formalization": HERE / "p1-formalization.md",
}
SOURCE.update({path.stem: path for path in sorted((HERE / "cells").glob("*.md"))})

PREAMBLE = r"""% !TEX program = xelatex
% Generated by docs/latex/build.py from the sources pinned in sources.json.
\documentclass[11pt,a4paper]{article}
\usepackage[a4paper,margin=25mm]{geometry}
\usepackage{fontspec}
\setmainfont{lmroman10-regular.otf}[BoldFont=lmroman10-bold.otf,ItalicFont=lmroman10-italic.otf,BoldItalicFont=lmroman10-bolditalic.otf]
\setsansfont{lmsans10-regular.otf}[BoldFont=lmsans10-bold.otf,ItalicFont=lmsans10-oblique.otf]
\setmonofont{JuliaMono-Regular.ttf}[Path=__CODE_FONT_PATH__,Scale=0.83]
\usepackage{amsmath,amssymb,mathtools}
\usepackage{graphicx,calc,longtable,booktabs,array}
\usepackage{fvextra}
\usepackage{xurl}
\usepackage[colorlinks=true,linkcolor=blue,urlcolor=blue,citecolor=blue]{hyperref}
\providecommand{\tightlist}{\setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt}
\setlength{\emergencystretch}{6em}
\begin{document}
"""
END = "\\end{document}\n"

# The proof sources use ordinary inline links; leave absolute URLs, including
# the original publication commit links, exactly as authored.
LINK = re.compile(r"(?P<prefix>\]\()(?P<target>[^\s)]+)(?P<suffix>(?:\s+\"[^\"]*\")?\))")


def pin_relative_links(markdown: str, source: Path) -> str:
    source_dir = source.relative_to(ROOT).parent

    def convert(match: re.Match[str]) -> str:
        target = match.group("target")
        parsed = urlsplit(target)
        if parsed.scheme or target.startswith(("/", "#", "//")):
            return match.group(0)
        destination = (ROOT / source_dir / parsed.path).resolve()
        try:
            relative = destination.relative_to(ROOT).as_posix()
        except ValueError as exc:
            raise ValueError(f"Link escapes repository: {source}: {target}") from exc
        pinned = BASE + quote(relative, safe="/-._~")
        if parsed.query:
            pinned += "?" + parsed.query
        if parsed.fragment:
            pinned += "#" + parsed.fragment
        return match.group("prefix") + pinned + match.group("suffix")

    markdown = LINK.sub(convert, markdown)
    return re.sub(
        r"https://github\.com/mpelteshki/climbing-to-the-frontier/(blob|tree)/main/",
        lambda match: f"https://github.com/mpelteshki/climbing-to-the-frontier/{match.group(1)}/{COMMIT}/",
        markdown,
    )


def normalize_display_math_delimiters(markdown: str) -> str:
    """Pandoc treats standalone dollar delimiters consistently across editions."""
    return re.sub(r"(?m)^[ \t]*\\[\[\]][ \t]*$", "$$", markdown)


def verified_source(problem: str) -> str:
    source = SOURCE[problem]
    name = source.relative_to(ROOT).as_posix()
    expected = MANIFEST["sha256"][name]
    try:
        data = source.read_bytes()
    except FileNotFoundError:
        data = None
    digest = hashlib.sha256(data).hexdigest() if data is not None else "missing"
    if digest != expected and name.startswith("cagent/"):
        try:
            data = subprocess.check_output(
                ["git", "show", f"{COMMIT}:{name}"], cwd=ROOT,
                stderr=subprocess.PIPE,
            )
        except (OSError, subprocess.CalledProcessError) as exc:
            raise ValueError(f"Cannot read pinned source {COMMIT}:{name}") from exc
        digest = hashlib.sha256(data).hexdigest()
    if digest != expected or data is None:
        raise ValueError(f"Source changed: {name}\nexpected {expected}\nactual   {digest}")
    return normalize_display_math_delimiters(pin_relative_links(data.decode("utf-8"), source))


def find_pandoc() -> str:
    candidates = [os.environ.get("PANDOC"), shutil.which("pandoc")]
    for candidate in candidates:
        if not candidate or not Path(candidate).is_file():
            continue
        try:
            version = subprocess.check_output([candidate, "--version"], text=True).splitlines()[0]
        except (OSError, subprocess.CalledProcessError):
            continue
        if version == "pandoc 3.11":
            return candidate
        print(f"Ignoring {candidate}: expected pandoc 3.11, got {version}", file=sys.stderr)
    raise RuntimeError("Pandoc 3.11 not found; set PANDOC to its executable path")


def normalize_text_symbols(body: str) -> str:
    """Keep code byte-for-byte while typesetting prose math glyphs safely."""
    substitutions = {
        "≤": r"\ensuremath{\leq}", "≥": r"\ensuremath{\geq}",
        "≠": r"\ensuremath{\ne}", "∀": r"\ensuremath{\forall}",
        "∃": r"\ensuremath{\exists}", "∈": r"\ensuremath{\in}",
        "→": r"\ensuremath{\to}", "←": r"\ensuremath{\leftarrow}",
        "∧": r"\ensuremath{\wedge}", "∨": r"\ensuremath{\vee}",
        "⊆": r"\ensuremath{\subseteq}", "∣": r"\ensuremath{\mid}",
        "∘": r"\ensuremath{\circ}", "⟨": r"\ensuremath{\langle}",
        "⟩": r"\ensuremath{\rangle}", "¬": r"\ensuremath{\neg}",
        "▸": r"\ensuremath{\triangleright}",
        "é": r"\'{e}", "í": r"\'{i}", "ó": r"\'{o}",
        "§": r"\S{}",
    }
    lines = []
    in_code = False
    for line in body.splitlines(keepends=True):
        if "\\begin{Verbatim}" in line:
            in_code = True
        if not in_code:
            for source, replacement in substitutions.items():
                line = line.replace(source, replacement)
        lines.append(line)
        if "\\end{Verbatim}" in line:
            in_code = False
    body = "".join(lines)
    return re.sub(
        r"\\texttt\{[0-9a-f]{40,64}\}",
        lambda match: r"\texttt{" + r"\allowbreak{}".join(
            match.group(0)[8:-1][i:i + 8]
            for i in range(0, len(match.group(0)[8:-1]), 8)
        ) + "}",
        body,
    )


def build(problem: str, pandoc: str) -> Path:
    result = subprocess.run(
        [pandoc, "-f", "markdown+tex_math_dollars+raw_tex", "-t", "latex",
         "--wrap=preserve", "--syntax-highlighting=none"],
        input=verified_source(problem), text=True, capture_output=True, check=True,
    )
    body = result.stdout
    body = body.replace("\\begin{verbatim}",
                        r'\begin{Verbatim}[breaklines,breakanywhere,fontsize=\footnotesize]')
    body = body.replace("\\end{verbatim}", "\\end{Verbatim}")
    body = normalize_text_symbols(body)
    output = (HERE / "cells" / f"{problem}.tex") if re.fullmatch(r"p[1-4]-c[1-6]", problem) else (HERE / f"{problem}.tex")
    font_path = "../fonts/" if output.parent.name == "cells" else "fonts/"
    preamble = PREAMBLE.replace("__CODE_FONT_PATH__", font_path)
    output.write_text(preamble + body + ("\n" if not body.endswith("\n") else "") + END,
                      encoding="utf-8")
    return output


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("problems", nargs="+", choices=(*SOURCE, "all"),
                        help="Documents to rebuild (p1–p4 and pX-cY cells)")
    args = parser.parse_args()
    pandoc = find_pandoc()
    problems = tuple(SOURCE) if "all" in args.problems else args.problems
    for problem in problems:
        output = build(problem, pandoc)
        print(f"{output.relative_to(ROOT)}: {hashlib.sha256(output.read_bytes()).hexdigest()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
